### ISSUE TITLE
How to manually fix a bad choice?

### ISSUE THREAD

**Issue by ghost** [denis-fokin/ChooseRuntime#17]
Hi,

After using choose runtime I get:

![image](https://user-images.githubusercontent.com/5411487/89911134-5e111300-dbf1-11ea-929a-1ef96f290fa7.png)

I get the same if I reinstall (sic!) IntellJ 2020.2. So I assume VM options refers 
to some  user settings. Where are they and how can I fix them?

**Comment by ghost** [comment]
Strange, restart Windows 10, and remove D\Software\Java2\jdk-16 did
get me out of the unfortunate situation.

**Comment by jburse** [comment]
Strange, restart Windows 10, and remove D\Software\Java2\jdk-16 did
get me out of the unfortunate situation.

**Comment by jburse** [comment]
Strange, restart Windows 10, and remove D\Software\Java2\jdk-16 did
get me out of the unfortunate situation.
