### ISSUE TITLE
Bintray was sunset and unable to get new JBR releases automatically

### ISSUE THREAD

**Issue by ZekerZhayard** [denis-fokin/ChooseRuntime#21]
since Bintray was sunset on May 1st, 2021, the latest of JBR which this plugin can catch is still 11.0.10+11-b1428.2, so are there any updating plan to get the new JBR releases?

**Comment by CrazyCoder** [comment]
This plug-in is obsolete, IDE now has a built-in feature to download JetBrains Runtime: https://intellij-support.jetbrains.com/hc/en-us/articles/206544879 .

**Comment by ZekerZhayard** [comment]
good to know!

**Comment by zd-dalibor** [comment]
@CrazyCoder  IDE 2020.2 does not have this built-in feature.
Is there any way to download jbrsdk 1.8 from somewhere else because https://dl.bintray.com is down
